triggers:
  - type: meya.regex
    properties:
        pattern: ^get (?P<url>https?://.+)$
states:
    first:
        component: meya.text
        properties:
            text: GET {{ flow.url }}
    make_request:
        flow: check
        data:
            url: '{{ flow.url }}'
