triggers:
  - type: meya.keyword
    properties:
        keyword: status
states:
    equal_check_state:
        component: meya.conditional_equal
        properties:
            value1: '{{ bot.running }}'
            value2: 'on'
        transitions:
            equal: started
            notequal: stopped
    stopped:
        component: meya.text
        properties:
            text: '❌ Stopped. Last: {{ bot.last_run }}'
        transitions:
            next: is_up
    started:
        component: meya.text
        properties:
            text: '✅ Running. Last: {{ bot.last_run }}'
    is_up:
        component: meya.text
        properties:
            text: '{{ bot.is_up }}'
    url:
        component: meya.text
        properties:
            text: '{{ bot.last_url }}'
        return: true
